### PR TITLE
Issue-75, handlers and service layers created, bugs fixed, new SQL sсripts created

### LINKED ISSUE #75: Handlers and service layers created, bugs fixed, new SQL sсripts created
`signup_handlers.go`: handlers layer, handle errors function declared
`models.go`: added struct `SignupRepository`, corrected mistakes (`ID` type string -> int)
`router.go`: inits routers
`credentials_repository.go`: updated
`signup_repository.go`: updated, modified with TextArray
`users_repository.go`: updated
`000005_re-creation_role.down.sql`: fixed bugs
`000005_re-creation_role.up.sql`: fixed bugs
`000006_change_id.up.sql`: drops unique `mobile_phone` constraint, `id`
type in tables `credentials` and `email_verification_tokens` changed into integer
`000006_change_id.down.sql`
`service.go`: service layer
`data.go`: validates user's entered data
`email.go`: validates user's entered email
`errors.go`: contains validation errors
`ims-api.yaml`: updated

Added function that handles errors.
Added error handlers to `signup_handlers.go`, `signup_repository.go`, `users_repository.go`, `credentials_repository.go`, `service.go`.

### PR DESCRIPTION
**Pull request by Krimyllex**
`signup_handlers.go`: handlers layer, handle errors function declared
`models.go`: added struct `SignupRepository`, corrected mistakes (`ID` type string -> int)
`router.go`: inits routers
`credentials_repository.go`: updated
`signup_repository.go`: updated, modified with TextArray
`users_repository.go`: updated
`000005_re-creation_role.down.sql`: fixed bugs
`000005_re-creation_role.up.sql`: fixed bugs
`000006_change_id.up.sql`: drops unique `mobile_phone` constraint, `id`
type in tables `credentials` and `email_verification_tokens` changed into integer
`000006_change_id.down.sql`
`service.go`: service layer
`data.go`: validates user's entered data
`email.go`: validates user's entered email
`errors.go`: contains validation errors
`ims-api.yaml`: updated

Added function that handles errors.
Added error handlers to `signup_handlers.go`, `signup_repository.go`, `users_repository.go`, `credentials_repository.go`, `service.go`.

Closes #75

### CODE REVIEW

File: pkg/ims/api/handlers/signup_handlers.go [hunk 1]
```diff
@@ -0,0 +1,190 @@
...
+		handleError(err, w)
+		return
+	}
+
+	request.FirstName = keyVal["first_name"]
+	request.LastName = keyVal["last_name"]
+	request.Email = keyVal["email"]
+	request.Password = keyVal["password"]
+
+	err = r.Body.Close()
```
Comment (taaraora) [inline pkg/ims/api/handlers/signup_handlers.go:128]: maybe it is better to close the body right after ReadAll call?

File: pkg/ims/api/handlers/signup_handlers.go [hunk 2]
```diff
@@ -0,0 +1,190 @@
...
+	var err error
+
+	body, err := ioutil.ReadAll(r.Body)
+	if err != nil {
+		handleError(err, w)
+		return
+	}
+
+	keyVal := make(map[string]string)
+	err = json.Unmarshal(body, &keyVal)
```
Comment (taaraora) [inline pkg/ims/api/handlers/signup_handlers.go:71]: unmarshal it directly in `SignupRequest`

File: pkg/ims/api/handlers/signup_handlers.go [hunk 3]
```diff
@@ -0,0 +1,190 @@
...
+	var request models.SignupRequest
+	var err error
+
+	body, err := ioutil.ReadAll(r.Body)
+	if err != nil {
+		handleError(err, w)
+		return
+	}
+
+	keyVal := make(map[string]string)
```
Comment (taaraora) [inline pkg/ims/api/handlers/signup_handlers.go:70]: remove this map please it is not needed

File: pkg/ims/api/handlers/signup_handlers.go [hunk 4]
```diff
@@ -0,0 +1,190 @@
...
+		err = postgresql.ErrToMuchSymbols
+		handleError(err, w)
+		return
+	}
+
+	if keyVal["password"] == "" {
+		err = postgresql.ErrNoSymbols
+		handleError(err, w)
+		return
+	} else if len(keyVal["password"]) > 256 {
```
Comment (taaraora) [inline pkg/ims/api/handlers/signup_handlers.go:101]: make a separate package for all your validations functions.

File: pkg/ims/api/handlers/signup_handlers.go [hunk 5]
```diff
@@ -0,0 +1,190 @@
...
+		handleError(err, w)
+		return
+	} else if len(keyVal["last_name"]) > 256 {
+		err = postgresql.ErrToMuchSymbols
+		handleError(err, w)
+		return
+	}
+
+	if keyVal["password"] == "" {
+		err = postgresql.ErrNoSymbols
```
Comment (taaraora) [inline pkg/ims/api/handlers/signup_handlers.go:98]: Why this is PostgreSQL error?

File: pkg/ims/repository/postgresql/signup_repository.go [hunk 6]
```diff
@@ -7,58 +7,66 @@ import (
...
 }
 
 //InsertUser inserts user's data into DB
-func (sr *SignUpRepository) InsertUser(u *models.Users) error {
-	_, err := sr.db.Exec("INSERT INTO users(id,first_name, last_name, email, mobile_phone, created_at, modified_at, roles) VALUES($1, $2, $3, $4, $5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, $6)", u.ID, u.FirstName, u.LastName, u.Email, u.MobilePhone, u.Roles)
+func (sr *SignUpRepository) InsertUser(u *models.User) (error) {
+	var str string
+
+	for _, val := range u.Roles {
+		str = str + val + ","
```
Comment (taaraora) [inline pkg/ims/repository/postgresql/signup_repository.go:34]: please use TextArray instead of this

File: pkg/ims/api/handlers/signup_handlers.go [hunk 7]
```diff
@@ -0,0 +1,138 @@
...
+		return
+	}
+
+	err = r.Body.Close()
+	if err != nil {
+		handleError(err, w)
+		return
+	}
+
+	err = validation.Data(&request)
```
Comment (taaraora) [inline pkg/ims/api/handlers/signup_handlers.go:76]: please make an issue to refactor validate function to make it reusable.

File: pkg/ims/api/handlers/signup_handlers.go [hunk 8]
```diff
@@ -0,0 +1,138 @@
...
+		err = validation.ErrNoSymbols
+		handleError(err, w)
+		return
+	}
+
+	result, err := h.SignUpService.EmailAvailable(params["email"])
+	if err != nil {
+		handleError(err, w)
+		return
+	} else if result == true {
```
Comment (taaraora) [inline pkg/ims/api/handlers/signup_handlers.go:109]: What if result is not true?

File: pkg/ims/repository/postgresql/users_repository.go [hunk 9]
```diff
@@ -71,35 +71,59 @@ func (ur *UsersRepository) UpdateUser(u models.Users) error {
...
 	if err != nil {
 		return nil, err
 	}
 
 	return ToUser(u)
 }
 
-func ToUser(privatUser user) (*models.Users, error) {
+// CheckEmail returns email if it exists in DB or empty string
+func (ur *UsersRepository) CheckEmail (email string) (string, error) {
```
Comment (taaraora) [inline pkg/ims/repository/postgresql/users_repository.go:95]: This method is not needed, just use `GetUserByEmail`

File: pkg/ims/repository/postgresql/users_repository.go [hunk 10]
```diff
@@ -71,35 +71,59 @@ func (ur *UsersRepository) UpdateUser(u models.Users) error {
...
+	}
+
+	return emailVal, nil
+}
+
+// GetEmailByToken returns email by token
+func (ur *UsersRepository) GetEmailByToken (token *models.EmailVerificationTokens) (string, error) {
+	var email string
+
+	err := ur.DB.Get(&email, "SELECT (SELECT email FROM users WHERE id = email_verification_tokens.id) FROM email_verification_tokens WHERE verification_token = $1", token.VerificationToken)
```
Comment (taaraora) [inline pkg/ims/repository/postgresql/users_repository.go:110]: please make an issue to simplify this query

File: pkg/ims/service/service.go [hunk 11]
```diff
@@ -0,0 +1,111 @@
...
+	tok.VerificationToken = token()
+
+	cred.Salt = pwd.Salt(256 - len(request.Password))
+
+	cred.PasswordHash, err = pwd.Hash(request.Password, cred.Salt)
+	if err != nil {
+		return err
+	}
+
+	err = service.SignUpRepo.InsertUser(&user)
```
Comment (taaraora) [inline pkg/ims/service/service.go:53]: you need to start a transaction before making your first request to DB

Comment (Krimyllex) [reply pkg/ims/service/service.go:53]: I do not understand enough what do you mean

File: pkg/ims/api/handlers/signup_handlers.go (hunk 7 above)
Comment (Krimyllex) [reply pkg/ims/api/handlers/signup_handlers.go:76]: Issue created: https://github.com/omc-college/management-system/issues/100

File: pkg/ims/repository/postgresql/users_repository.go (hunk 10 above)
Comment (Krimyllex) [reply pkg/ims/repository/postgresql/users_repository.go:110]: Issue created: https://github.com/omc-college/management-system/issues/101

File: pkg/ims/service/service.go (hunk 11 above)
Comment (Krimyllex) [reply pkg/ims/service/service.go:53]: The problem was resolved at the zoom conference.

File: pkg/ims/api/handlers/signup_handlers.go [hunk 12]
```diff
@@ -0,0 +1,141 @@
...
+		return
+	}
+
+	err = h.SignUpService.SignUp(&request)
+	if err != nil {
+		handleError(err, w)
+		return
+	}
+
+	// Send Email Verification Token function must be here!
```
Comment (taaraora) [inline pkg/ims/api/handlers/signup_handlers.go:89]: this function should be added in service layer

File: pkg/ims/api/handlers/signup_handlers.go [hunk 13]
```diff
@@ -0,0 +1,141 @@
...
+	} else if result == true {
+		err = validation.ErrEmailExists
+		handleError(err, w)
+		return
+	} else {
+		fmt.Fprintf(w, "email is not occupied")
+	}
+}
+
+func (h *SignUpHandler)EmailVerificationToken(w http.ResponseWriter, r *http.Request) {
```
Comment (taaraora) [inline pkg/ims/api/handlers/signup_handlers.go:119]: Maybe `EmailVerificationToken` should be named  `CheckEmailVerificationToken`

File: pkg/ims/models/models.go [hunk 14]
```diff
@@ -2,18 +2,19 @@ package models
...
-	Roles       []string `json:"roles"`
-	Verified    bool     `json:"verified"`
+type User struct {
+	ID          int      	`json:"id" db:"id"`
+	FirstName   string   	`json:"first_name" db:"first_name"`
+	LastName    string   	`json:"last_name" db:"last_name"`
+	Email       string   	`json:"email" db:"email"`
+	MobilePhone string   	`json:"mobile_phone" db:"mobile_phone"`
+	CreatedAt   time.Time   `json:"created_at" db:"created_at"`
+	ModifiedAt  time.Time   `json:"modified_at" db:"modified_at"`
```
Comment (taaraora) [inline pkg/ims/models/models.go:15]: make an issue to make this field pointer.

File: pkg/ims/repository/postgresql/credentials_repository.go [hunk 15]
```diff
@@ -7,26 +7,18 @@ import (
 )
 
 type CredRepository struct {
-	db *sqlx.DB
+	DB sqlx.Ext
```
Comment (taaraora) [inline pkg/ims/repository/postgresql/credentials_repository.go:10]: maybe we can make it unexportable?

File: pkg/ims/service/service.go [hunk 16]
```diff
@@ -0,0 +1,153 @@
...
+
+	return nil
+}
+
+func (service *SignUpService) EmailAvailable (email string) (bool, error) {
+	var user *models.User
+	var exist bool
+	var err error
+
+	tx, err := service.db.Beginx()
```
Comment (taaraora) [inline pkg/ims/service/service.go:92]: The explicit transaction is not needed here.

File: pkg/ims/models/models.go (hunk 14 above)
Comment (Krimyllex) [reply pkg/ims/models/models.go:15]: Issue created: https://github.com/omc-college/management-system/issues/110
